# Generated by Django 4.1 on 2022-09-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_address', models.CharField(default=None, max_length=100)),
                ('user_phone', models.CharField(default=None, max_length=10)),
            ],
        ),
    ]
