# Generated by Django 4.1 on 2022-09-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesome_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=20)),
                ('admin_password', models.CharField(max_length=20)),
            ],
        ),
    ]
